AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./search-photos
      Description: "Lambda function for CD"
      MemorySize: 128
      Timeout: 30
      Role: ""
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index-photos
      Description: "Lambda function for CD"
      MemorySize: 128
      Timeout: 30
      Role: ""
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda3:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: helper-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf0
      Description: "Lambda function for CD"
      MemorySize: 128
      Timeout: 30
      Role: ""
      Environment:
        Variables:
          REGION: us-east-1
